<?php
/**
 * Plugin Name:       Connector for Propstack
 * Description:       Allows you to present your objects from Propstack in your website.
 * Requires at least: 6.0
 * Requires PHP:      8.2
 * Version:           @@VersionNumber@@
 * Author:            laOlaWeb
 * Author URI:        https://laolaweb.com
 * License:           GPL-2.0-or-later
 * License URI:       https://www.gnu.org/licenses/gpl-2.0.html
 * Text Domain:       connector-for-propstack
 *
 * @package connector-for-propstack
 */

// prevent direct access.
defined( 'ABSPATH' ) || exit;

use ConnectorForPropstack\Plugin\Init;
use ConnectorForPropstack\Plugin\Installer;

// do nothing if the PHP version is not 8.2 or newer.
if ( PHP_VERSION_ID < 80200 ) { // @phpstan-ignore smaller.alwaysFalse
	return;
}

// set the version number.
const CFPROP_VERSION = '@@VersionNumber@@';

// save plugin-path.
const CFPROP_PLUGIN = __FILE__;

// get autoloader generated by composer.
require_once __DIR__ . '/vendor/autoload.php';

// on activation.
register_activation_hook( CFPROP_PLUGIN, array( Installer::get_instance(), 'activation' ) );

// on deactivation.
register_deactivation_hook( CFPROP_PLUGIN, array( Init::get_instance(), 'deactivation' ) );

add_action(
	'plugins_loaded',
	static function () {
		Init::get_instance()->init();
	}
);
