<?php
/**
 * Tasks to run during uninstallation of this plugin.
 *
 * @package connector-for-propstack
 */

use ConnectorForPropstack\Plugin\Uninstaller;

// if uninstall.php has not called by WordPress, die.
if ( ! defined( 'WP_UNINSTALL_PLUGIN' ) ) {
	exit;
}

// prevent direct access.
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

// do nothing if the PHP version is not 8.2 or newer.
if ( PHP_VERSION_ID < 80200 ) { // @phpstan-ignore smaller.alwaysFalse
	return;
}

// set the version number.
const CONNECTOR_FOR_PROPSTACK_VERSION = '@@VersionNumber@@';

// save plugin-path.
const CONNECTOR_FOR_PROPSTACK_PLUGIN = __FILE__;

// get autoloader generated by composer.
require_once __DIR__ . '/vendor/autoload.php';

// run uninstaller.
Uninstaller::get_instance()->run();
